# Generated by Django 3.1.2 on 2020-10-27 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.SmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('vietnamese', 'vietnamese'), ('english', 'english'), ('other', 'other')], max_length=10)),
                ('category', models.CharField(choices=[('book', 'book'), ('article', 'article'), ('slide', 'slide'), ('test', 'test')], max_length=7)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
                'managed': True,
            },
        ),
    ]
